### ISSUE TITLE
user and group ID of `/usr/local/share/last-tool/files`

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#15]
I was checking last06e (to do the same I did for issue #14). Is it intentional that `files` has a uid and gid  different that `ocs`, or is it a glitch?
```
ocs@last06e:/usr/local/share/last-tool$ ls -l
total 112
drwxr-xr-x 2 ocs  ocs  4096 Jan 30 12:49 bin
drwxr-xr-x 4 1002 1003 4096 Jan 30 12:49 files
drwxr-xr-x 2 ocs  ocs  4096 Jan 30 12:49 lib
drwxr-xr-x 2 ocs  ocs  4096 Jan 30 14:29 sections
```

**Comment by blumzi** [comment]
Cannot reproduce.  I checked many machines, including newly installed, no problem.
Seems like a last06e speciffic glitch.  last06e is destined to move South and will be re-visited beforehand.
