### ISSUE TITLE
last-parallel-rsync fails with status 255 and 10

### ISSUE THREAD

**Issue by noralinn** [blumzi/LAST_tools#19]
ocs@last02w:/last02w/data2/archive/LAST.01.02.04/2022$ last-parallel-rsync -s .
[INFO] Source: "/last02w/data2/archive/LAST.01.02.04/2022"
[INFO] Target: "last@marvin.weizmann.ac.il:/BIGDATA/last/data/temp"
[INFO] Gathering list of files ...
[INFO] Splitting workload among  processes ...
[INFO] Synchronizing chunk #1 (of 10) ...
[INFO] Synchronizing chunk #2 (of 10) ...
[INFO] Synchronizing chunk #3 (of 10) ...
[INFO] Synchronizing chunk #4 (of 10) ...
[INFO] Synchronizing chunk #5 (of 10) ...
[INFO] Synchronizing chunk #6 (of 10) ...
[INFO] Synchronizing chunk #8 (of 10) ...
[INFO] Synchronizing chunk #7 (of 10) ...
[INFO] Synchronizing chunk #9 (of 10) ...
[INFO] Synchronizing chunk #10 (of 10) ...
[FAIL] Chunk #6 (of 10) failed with status: 255
[FAIL] Chunk #2 (of 10) failed with status: 255
[FAIL] Chunk #10 (of 10) failed with status: 255
[FAIL] Chunk #4 (of 10) failed with status: 255
[FAIL] Chunk #8 (of 10) failed with status: 10
[FAIL] Chunk #1 (of 10) failed with status: 255
[FAIL] Chunk #9 (of 10) failed with status: 255
[FAIL] Chunk #3 (of 10) failed with status: 255
[FAIL] Chunk #7 (of 10) failed with status: 255

**Comment by blumzi** [comment]
old and not relevant any more
