### ISSUE TITLE
reminder: update host list, MACmap IPs etc for the newly deployed units

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#21]
Making a ticket of it just to track it. We are adding the new LAST units 3,4,5,6 and 10. While staging I have locally changed back and forth IP addresses in `/usr/local/files/last-tool/MACmap` from subnet 10.23.2. to .3 and viceversa. On each machine I worked there were some ad hoc differences, now things can be straightened in the master source file.
Also, once installed, the new hosts `last03..6,10e/w` can be added to the list of known hosts so `/bin/asroot last-tool....` finds them.

**Comment by blumzi** [comment]
This is an old ticket, it's fixed by now.
Reminder: ``last-hosts --deployed`` produces an updated list of deployed machines (for more see: ``last-hosts --help``)
