### ISSUE TITLE
missing `/home/ocs/.ssh/pass.enc` on last05e

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#28]
I get this in the course of running `last-asroot -c "last-tool --nodeps enforce last-software --repo LAST/LAST_OCS"`.
```
[SECT] last05e:
[FAIL] ssh failure (status=1, err="Can't open /home/ocs/.ssh/pass.enc for reading, No such file or directory
140421183821120:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/home/ocs/.ssh/pass.enc','rb')
140421183821120:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
sudo: no password was provided")
```
 last05e was the computer which was replaced recently. What is the command which should have generated ts file?

**Comment by EastEriq** [comment]
I've tried `sudo last-tool enforce ssh` on last05e but that did not fix it.

**Comment by blumzi** [comment]
Commit 7f2f6e1 fixes 'last-tool enforce/check ssh' to handle the encrypted password file
