### ISSUE TITLE
`last-tool -n enforce last-software --repo` doesn't pull more than one repo

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#29]
e.g. `sudo last-tool -n enforce last-software --repo LAST/LAST_OCS --repo LAST/LAST_QHYccd` pulls only LAST_OCS. I thought I remember that the command should allow a list of repositories. Other syntaxes I tried, like `--repo LAST/LAST_OCS,LAST/LAST_QHYccd` don't work. Or have I misunderstood the option?
(I was not able to find in the wiki, or to get a command line help specifically on this)

**Comment by EastEriq** [comment]
ping, it has hit me again this morning

**Comment by blumzi** [comment]
fixed w/ commit b4e6e1b
