### ISSUE TITLE
why token DiChecco?

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#3]
```
$ more /usr/local/share/last-tool/files/github-tokens 
github_token["Development"]="ghp_ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
github_token["DiChecco"]="ghp_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
```
It's Cecco di Ronchitti (da Bruzene).

**Comment by blumzi** [comment]
So, would Checco be OK?

**Comment by EastEriq** [comment]
Shit, I forgot!



our GitHub access token has been found in blumzi/LAST_tools and revoked | our GitHub access token has been found in blumzi/LAST_tools and revoked |  
-- | -- | --
our GitHub access token has been found in blumzi/LAST_tools and revoked
 

our GitHub access token has been found in blumzi/LAST_tools and revoked
 
 
Your GitHub Personal Access Token has been revoked
 

A recent scan found a valid GitHub Personal Access Token linked to your GitHub account in the description of [this](https://github.com/blumzi/LAST_tools/issues/3#issue-1341714760) issue. We have revoked the key to protect your data from unauthorized access. Any integrations using this token will no longer be able to authenticate to GitHub.

**Comment by EastEriq** [comment]
> So, would Checco be OK?

Cecco

**Comment by EastEriq** [comment]
Anyway now we have to recreate the token, and propagate. I forgot that you should never quote them in clear. Do you log into CeccoDiRonchitti and do it, or I?

**Comment by blumzi** [comment]
When was the token revoked?

It is a very long time that the tokens are not stored in the repo

**Comment by EastEriq** [comment]
recreated, and sent you by PM. Also edited the initial issue text, albeit too late.

**Comment by blumzi** [comment]
I changed and pushed the files.  Will re-make and distribute last-tool now

**Comment by EastEriq** [comment]
sorry for the nuisance
