### ISSUE TITLE
Last0 wants to install linux updates

### ISSUE THREAD

**Issue by PolishookDavid** [blumzi/LAST_tools#5]
A popup window on last0: "Not all updates can be installed"
What should I do?
"Partial Upgrade"
"Continue"
"Close"

<img width="706" alt="Screen Shot 2022-09-06 at 9 41 55" src="https://user-images.githubusercontent.com/45033848/188565546-97fea2b7-6eb4-43af-9c22-60c7f8013fce.png">

**Comment by EastEriq** [comment]
All machines check periodically for updates. We informally decided to decline them for sanity, but Arie has not yet looked into a way of disabling the check, with all his dialogs. One would think it should be a big deal, according to what can be found on the net. E.g., https://itsfoss.com/auto-updates-ubuntu/, https://linuxnightly.com/how-to-disable-automatic-updates-in-ubuntu/. `/etc/apt/apt.conf.d/20auto-upgrades` should contain zeros (and it does on last0), but maybe that is not all of it.

**Comment by EastEriq** [comment]
Maybe one needs to add?
```
APT::Periodic::AutocleanInterval "0";
```

**Comment by blumzi** [comment]
Commit 37d47a1 disables the service apt-daily-upgrade
