### ISSUE TITLE
`enforce last-software` on multiple machines

### ISSUE THREAD

**Issue by EastEriq** [blumzi/LAST_tools#7]
I forgot if we already mentioned, maybe we did and it is even written somewhere, in case forgive me.
Could you suggest, and write down in https://github.com/blumzi/LAST_tools/wiki/tips, an one-liner for doing `sudo last-tool --nodeps enforce last-software` on a set of machines?

**Comment by blumzi** [comment]
See tips-and-tricks [here](https://github.com/blumzi/LAST_tools/wiki/do_something_on_last_machines).

**Comment by EastEriq** [comment]
Excellent explanation, thanks
